### ISSUE TITLE
forgot password button

### ISSUE THREAD

**Issue by kermit666** [jennschiffer/pixelChat#10]
Is there a way to reset a password somehow? For the normal registration (just email + password). Something was taking very long loading during account creation so we restarted the app and then the password credentials are never accepted when we try to log in (user: saaki).

**Comment by kermit666** [comment]
I'm talking about the Android app actually. Looking at the source, I don't think that this code is actually for that, or?

**Comment by jennschiffer** [comment]
This is a web app, there is nothing specific for Android and all the login stuff is through Twitter. If you forgot your Twitter password, you'll need to do it through Twitter's app or website!

**Comment by kermit666** [comment]
Oh. Maybe then I opened the issue In the wrong place then. I am talking about the PixelChat app for Android available on Google Play. Of the 3 buttons there for Facebook, Twitter and email we selected email and that's where the problem appeared.

**Comment by jennschiffer** [comment]
You must be thinking of this: https://play.google.com/store/apps/details?id=com.dapper.pixelchat&hl=en
